application: foodsafely
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static 
  static_dir: static

- url: /static/css 
  static_dir: static/css

- url: .*
  script: main.app 


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
